server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: med-flink-jobmanager
    static_configs:
      - targets:
          - localhost
        labels:
          job: med-flink
          component: jobmanager
          __path__: /var/log/flink/jobmanager/*.log

  - job_name: med-flink-taskmanager
    static_configs:
      - targets:
          - localhost
        labels:
          job: med-flink
          component: taskmanager
          __path__: /var/log/flink/taskmanager/*.log